<?php
$form_url = URL('', $request->getAllQueryParameters());
?>
<div class="container" style="width:480px;margin-top:2em">
    <div class="well clearfix">
        <form action="<?= H($form_url) ?>" method="POST" style="margin:.5em">
            <input name="scope" type="hidden" value="<?= H($request->query('scope')) ?>" />

            <h4><?= T('%s 希望使用您在本系统的以下信息:', '<strong>'.$client['client_name'].'</strong>') ?></h4>
            
            <blockquote>
                <?= H(T('个人基本信息和联系方式')) ?>
            </blockquote>

            <div class="controls pull-right">
                <button name="authorize" value="authorize" class="btn btn-success"><i class="icon-ok"></i> <?= H(T('我同意授权')) ?></button>
                <button value="cancel" class="btn btn-danger"><i class="icon-remove"></i> <?= H(T('我不同意')) ?></button>
            </div>
        </form>
    </div>
</div>